export const BID_CREATE_SUCCESS = 'BID_CREATE_SUCCESS'
export const BID_CREATE_FAIL = 'BID_CREATE_FAIL'
export const BID_CREATE_RESET = 'BID_CREATE_RESET'

export const BID_LIST_SUCCESS = 'BID_LIST_SUCCESS'
export const BID_LIST_FAIL = 'BID_LIST_FAIL'
export const BID_LIST_RESET = 'BID_LIST_RESET'

